name: Events Demo 1
on:
  pull_request:
    types: [opened, edited]
    branches:
      - main
      - "dev-*" # dev-new dev-this-is-new
      - "feat/**" # feat/new feat/new/button
      # developer-1
  workflow_dispatch:
  push:
    branches:
      - main
      - "dev-*" # dev-new dev-this-is-new
      - "feat/**" # feat/new feat/new/button
      # developer-1
    paths-ignore:
      - "github/workflows/*" # it basicaly means that if we pushed to the three specified branch
      # and we didn't change anything in the path mentioned, trigger this workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
